### ISSUE TITLE
fin doesn't install .awk files

### ISSUE THREAD

**Issue by oe** [fisherman/fin#9]
when i try to install `fisherman/z`, it doesn't seem to link the `z.awk` files into the `$fishpath/functions` directory (as running `z` tells me)

**Comment by dideler** [comment]
I believe this project is deprecated, see https://github.com/fisherman/fisherman/issues/204#issuecomment-212747453

**Comment by fene** [comment]
oh, that sucks

**Comment by jbucaran** [comment]
Sorry for the confusion, @dideler is talking about an older fin, which was deprecated. Since there is a _new_ fin, which is **not** deprecated, I am cross linking this with a thread that explains the issue in more detail.

Cheers!

* https://github.com/jbucaran/awesome-fish/issues/32#issuecomment-277403234

**Comment by jbucaran** [comment]
/cc @pnn 

Sorry for the confusion, @dideler is talking about an older fin, which was deprecated. Since there is a _new_ fin, which is **not** deprecated, I am cross linking this with a thread that explains the issue in more detail.

Cheers!

* https://github.com/jbucaran/awesome-fish/issues/32#issuecomment-277403234

**Comment by jbucaran** [comment]
@pnn Hi! Are you still using fin perchance? If so, I'd love to take a look at this issue and help out.

**Comment by pnn** [comment]
@jbucaran yeah!

**Comment by jbucaran** [comment]
The relevant code is here:
* https://github.com/fisherman/fin/blob/master/fin.fish#L155

And yes, you're right this is not a feature in fin. See [fisherman vs fin](https://github.com/fisherman/fin/issues/5).
